# Generated by Django 3.0.6 on 2022-05-08 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=15, verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': 'Teachers'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('stdgroup', models.ForeignKey(db_column='Группа студента', on_delete=django.db.models.deletion.DO_NOTHING, to='main.StudentGroup')),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='оценка')),
                ('created', models.DateField(verbose_name='дата')),
                ('discipline', models.ForeignKey(db_column='Дисциплина', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Discipline')),
                ('student', models.ForeignKey(db_column='Студент', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Student')),
                ('teacher', models.ForeignKey(db_column='Преподаватель', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(db_column='Дисциплина', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Discipline')),
                ('group', models.ForeignKey(db_column='Группа', on_delete=django.db.models.deletion.DO_NOTHING, to='main.StudentGroup')),
                ('teacher', models.ForeignKey(db_column='Преподаватель', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='group',
            field=models.ForeignKey(db_column='Группа', on_delete=django.db.models.deletion.DO_NOTHING, to='main.StudentGroup'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(db_column='Преподаватель данной дисциплины', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Teacher'),
        ),
    ]
